import Header from "../components/Header";
import Checkout from "../components/Checkout";
import Head from "next/head";
function checkout() {
  return (
    <div>
        <Head>
        <title>Agri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/AGRI (1).ico" />
      </Head>
      <Header /> <Checkout />
    </div>
  );
}
export default checkout;
