import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";
import { BrowserRouter as Router, Switch, Route } from "react-router-dom";
import { auth } from "../components/firebase";
import { useStateValues } from "../components/StateProvider";
import { useEffect } from "react";
import { useRouter } from "next/router";
import axios from "axios";
export default function Home({ results }) {
  const [{ _ }, dispatch] = useStateValues();
  const router = useRouter();

  useEffect(() => {
    //will only run once when the app component loads
    auth.onAuthStateChanged((authUser) => {
      console.log("thu user is", authUser);
      if (authUser) {


        const get = async () => {
          const response = await axios(
            {
              method:'get',
          url:`https://jeeback.herokuapp.com/api/custumer/${authUser.uid}`,
        

            }
          );
          console.log(response.data);
        

  
       
          dispatch({
         type: "SET_USER",
         user: authUser,
         user1: response.data,
          username:response.data.fullname,
       adresse:response.data.adresse
        
       })
        };

          get().catch((error) => {console.log('')});
          //dispatch({
          //  type: "SET_USER",
          //  user: authUser,
            //user1: response.data,
             //username:response.data.fullname,
          //adresse:response.data.adresse
           
         // })


       
      } else {
        dispatch({
          type: "SET_USER",
          user: null,
          user1: null,
           username:"",
        adresse:""
         
        });
      }
    });
  }, []);

  useEffect(() => {


   }, []);


  
  return (
    <div>
      <Head>
        <title>Agri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/AGRI (1).ico" />
      </Head>

      <Header />
      <Nav count={5} />
      <Results results={results.products} />
    </div>
  );
}

export const getServerSideProps = async (context) => {
  

  const category = context.query.category;
  const product = context.query.product;
  const page = context.query.page;
  console.log(category);
  if (product) {
    const response = await fetch(
      `https://jeeback.herokuapp.com/api/products/name/${product}`
    );
    const results = await response.json();
    if (results.length > 0) {
      return {
        props: {
          results,
        },
      };
    }
  }

  if(page){
    const response = await fetch(
      `https://jeeback.herokuapp.com/api/products${
       requests[category]?.url || requests.fetchALL.url
     }?page=${page-1}`
  );
  const results = await response.json();
  const count =results.count;
  console.log(results.count);
 
  return {
    props: {
      results,
    },
  };

  }

//const results=[{"id":1,"title":"Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops","price":109.95,"description":"Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday","category":"men's clothing","image":"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg","rating":{"rate":3.9,"count":120}},{"id":2,"title":"Mens Casual Premium Slim Fit T-Shirts ","price":22.3,"description":"Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.","category":"men's clothing","image":"https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg","rating":{"rate":4.1,"count":259}},{"id":3,"title":"Mens Cotton Jacket","price":55.99,"description":"great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.","category":"men's clothing","image":"https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg","rating":{"rate":4.7,"count":500}}];
  
const response = await fetch(
  `https://jeeback.herokuapp.com/api/products${
   requests[category]?.url || requests.fetchALL.url
 }?page=0`
);
const results = await response.json();
const count =results.count;
console.log(results.count);
  
  

  return {
    props: {
      results,
    },
  };
};


