import Head from "next/head";
import Header from "../components/Header";
import Payment from "../components/Payment";

function payment() {
  return (
    <div>
        <Head>
        <title>Agri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/AGRI (1).ico" />
      </Head>
      <Header />
      <Payment />
    </div>
  );
}

export default payment;
